import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

const [sourceDir = 'lighthouse-report', outDir = '_site/lighthouse'] = process.argv.slice(2);
const manifest = JSON.parse(readFileSync(join(sourceDir, 'manifest.json'), 'utf8'));

mkdirSync(outDir, { recursive: true });

const pct = (score) => (typeof score === 'number' ? Math.round(score * 100) : '–');
const rows = manifest
    .filter((entry) => entry.isRepresentativeRun)
    .map((entry) => {
        const file = basename(entry.htmlPath);
        copyFileSync(entry.htmlPath, join(outDir, file));
        const page = new URL(entry.url).pathname;
        const s = entry.summary;
        return `<tr><td><a href="./${file}">${page}</a></td><td>${pct(s.performance)}</td><td>${pct(s.accessibility)}</td><td>${pct(s['best-practices'])}</td><td>${pct(s.seo)}</td></tr>`;
    })
    .join('\n');

writeFileSync(
    join(outDir, 'index.html'),
    `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Lighthouse | Danish Ali</title>
<link rel="stylesheet" href="../assets/blog.css">
</head>
<body>
<div class="wrap">
<nav class="top-nav"><a href="../">← Danish Ali</a><a href="../report/">Test report</a></nav>
<main>
<h1>Lighthouse scores</h1>
<p class="meta">Generated by Lighthouse CI on every deploy. Updated ${new Date().toUTCString()}.</p>
<table>
<thead><tr><th>Page</th><th>Performance</th><th>Accessibility</th><th>Best practices</th><th>SEO</th></tr></thead>
<tbody>
${rows}
</tbody>
</table>
</main>
</div>
</body>
</html>
`,
);
